// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
/*import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9JrJoEaPMXLfVlD4OSO-Oz1JNxXkxiJY',
    appId: '1:322460520275:web:036b121136293c935f1ba6',
    messagingSenderId: '322460520275',
    projectId: 'gourmet-pass',
    authDomain: 'gourmet-pass.firebaseapp.com',
    storageBucket: 'gourmet-pass.firebasestorage.app',
    measurementId: 'G-9WYG6X9XYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8_C_h6QA7w4f0rIBNyyu5rFyBFUDmpiY',
    appId: '1:322460520275:android:1555afd0f446913f5f1ba6',
    messagingSenderId: '322460520275',
    projectId: 'gourmet-pass',
    storageBucket: 'gourmet-pass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-5zW6tX-unZT2GmlFjiLQzcPXlOiL-kI',
    appId: '1:322460520275:ios:90841189906750e35f1ba6',
    messagingSenderId: '322460520275',
    projectId: 'gourmet-pass',
    storageBucket: 'gourmet-pass.firebasestorage.app',
    iosBundleId: 'com.example.gourmetpass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-5zW6tX-unZT2GmlFjiLQzcPXlOiL-kI',
    appId: '1:322460520275:ios:90841189906750e35f1ba6',
    messagingSenderId: '322460520275',
    projectId: 'gourmet-pass',
    storageBucket: 'gourmet-pass.firebasestorage.app',
    iosBundleId: 'com.example.gourmetpass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9JrJoEaPMXLfVlD4OSO-Oz1JNxXkxiJY',
    appId: '1:322460520275:web:d74414a6898374eb5f1ba6',
    messagingSenderId: '322460520275',
    projectId: 'gourmet-pass',
    authDomain: 'gourmet-pass.firebaseapp.com',
    storageBucket: 'gourmet-pass.firebasestorage.app',
    measurementId: 'G-9D6TB33494',
  );

}*/